/*
 * FancyBox - jQuery Plugin
 * Simple and fancy lightbox alternative
 *
 * Examples and documentation at: http://fancybox.net
 * 
 * Copyright (c) 2008 - 2010 Janis Skarnelis
 * That said, it is hardly a one-person project. Many people have submitted bugs, code, and offered their advice freely. Their support is greatly appreciated.
 * 
 * Version: 1.3.4 (11/11/2010)
 * Requires: jQuery v1.3+
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */

(function(a){var l,q,r,e,y,k,z,h,v,w,o=0,d={},m=[],n=0,c={},i=[],B=null,s=new Image,D=/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i,O=/[^\.]\.(swf)\s*$/i,E,F=1,u=0,t="",p,g,j=!1,x=a.extend(a("<div/>")[0],{prop:0}),G=a.browser.msie&&7>a.browser.version&&!window.XMLHttpRequest,H=function(){q.hide();s.onerror=s.onload=null;B&&B.abort();l.empty()},I=function(){!1===d.onError(m,o,d)?(q.hide(),j=!1):(d.titleShow=!1,d.width="auto",d.height="auto",l.html('<p id="fancybox-error">The requested content cannot be loaded.<br />Please try again later.</p>'),
A())},C=function(){var b=m[o],f,c,e,g,i,h;H();d=a.extend({},a.fn.fancybox.defaults,"undefined"==typeof a(b).data("fancybox")?d:a(b).data("fancybox"));h=d.onStart(m,o,d);if(!1===h)j=!1;else{"object"==typeof h&&(d=a.extend(d,h));e=d.title||(b.nodeName?a(b).attr("title"):b.title)||"";b.nodeName&&!d.orig&&(d.orig=a(b).children("img:first").length?a(b).children("img:first"):a(b));""===e&&(d.orig&&d.titleFromAlt)&&(e=d.orig.attr("alt"));f=d.href||(b.nodeName?a(b).attr("href"):b.href)||null;if(/^(?:javascript)/i.test(f)||
"#"==f)f=null;d.type?(c=d.type,f||(f=d.content)):d.content?c="html":f&&(c=f.match(D)?"image":f.match(O)?"swf":a(b).hasClass("iframe")?"iframe":0===f.indexOf("#")?"inline":"ajax");if(c)switch("inline"==c&&(b=f.substr(f.indexOf("#")),c=0<a(b).length?"inline":"ajax"),d.type=c,d.href=f,d.title=e,d.autoDimensions&&("html"==d.type||"inline"==d.type||"ajax"==d.type?(d.width="auto",d.height="auto"):d.autoDimensions=!1),d.modal&&(d.overlayShow=!0,d.hideOnOverlayClick=!1,d.hideOnContentClick=!1,d.enableEscapeButton=
!1,d.showCloseButton=!1),d.padding=parseInt(d.padding,10),d.margin=parseInt(d.margin,10),l.css("padding",d.padding+d.margin),a(".fancybox-inline-tmp").unbind("fancybox-cancel").bind("fancybox-change",function(){a(this).replaceWith(k.children())}),c){case "html":l.html(d.content);A();break;case "inline":if(!0===a(b).parent().is("#fancybox-content")){j=!1;break}a('<div class="fancybox-inline-tmp" />').hide().insertBefore(a(b)).bind("fancybox-cleanup",function(){a(this).replaceWith(k.children())}).bind("fancybox-cancel",
function(){a(this).replaceWith(l.children())});a(b).appendTo(l);A();break;case "image":j=!1;a.fancybox.showActivity();s=new Image;s.onerror=function(){I()};s.onload=function(){j=true;s.onerror=s.onload=null;d.width=s.width;d.height=s.height;a("<img />").attr({id:"fancybox-img",src:s.src,alt:d.title}).appendTo(l);J()};s.src=f;break;case "swf":d.scrolling="no";g='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+d.width+'" height="'+d.height+'"><param name="movie" value="'+f+'"></param>';
i="";a.each(d.swf,function(b,a){g=g+('<param name="'+b+'" value="'+a+'"></param>');i=i+(" "+b+'="'+a+'"')});g+='<embed src="'+f+'" type="application/x-shockwave-flash" width="'+d.width+'" height="'+d.height+'"'+i+"></embed></object>";l.html(g);A();break;case "ajax":j=!1;a.fancybox.showActivity();d.ajax.win=d.ajax.success;B=a.ajax(a.extend({},d.ajax,{url:f,data:d.ajax.data||{},error:function(b){b.status>0&&I()},success:function(b,a,c){if((typeof c=="object"?c:B).status==200){if(typeof d.ajax.win==
"function"){h=d.ajax.win(f,b,a,c);if(h===false){q.hide();return}if(typeof h=="string"||typeof h=="object")b=h}l.html(b);A()}}}));break;case "iframe":J()}else I()}},A=function(){var b=d.width,c=d.height,b=-1<b.toString().indexOf("%")?parseInt((a(window).width()-2*d.margin)*parseFloat(b)/100,10)+"px":"auto"==b?"auto":b+"px",c=-1<c.toString().indexOf("%")?parseInt((a(window).height()-2*d.margin)*parseFloat(c)/100,10)+"px":"auto"==c?"auto":c+"px";l.wrapInner('<div style="width:'+b+";height:"+c+";overflow: "+
("auto"==d.scrolling?"auto":"yes"==d.scrolling?"scroll":"hidden")+';position:relative;"></div>');d.width=l.width();d.height=l.height();J()},J=function(){var b,f;q.hide();if(e.is(":visible")&&!1===c.onCleanup(i,n,c))a.event.trigger("fancybox-cancel"),j=!1;else{j=!0;a(k.add(r)).unbind();a(window).unbind("resize.fb scroll.fb");a(document).unbind("keydown.fb");e.is(":visible")&&"outside"!==c.titlePosition&&e.css("height",e.height());i=m;n=o;c=d;if(c.overlayShow){if(r.css({"background-color":c.overlayColor,
opacity:c.overlayOpacity,cursor:c.hideOnOverlayClick?"pointer":"auto",height:a(document).height()}),!r.is(":visible")){if(G)a("select:not(#fancybox-tmp select)").filter(function(){return"hidden"!==this.style.visibility}).css({visibility:"hidden"}).one("fancybox-cleanup",function(){this.style.visibility="inherit"});r.show()}}else r.hide();g=P();t=c.title||"";u=0;h.empty().removeAttr("style").removeClass();if(!(!1===c.titleShow||" "===c.title))if((t=a.isFunction(c.titleFormat)?c.titleFormat(t,i,n,c):
t&&t.length?"float"==c.titlePosition?'<table id="fancybox-title-float-wrap" cellpadding="0" cellspacing="0"><tr><td id="fancybox-title-float-left"></td><td id="fancybox-title-float-main">'+t+'</td><td id="fancybox-title-float-right"></td></tr></table>':'<div id="fancybox-title-'+c.titlePosition+'">'+t+"</div>":!1)&&""!==t)switch(h.addClass("fancybox-title-"+c.titlePosition).html(t).appendTo("body").show(),c.titlePosition){case "inside":h.css({width:g.width-2*c.padding,marginLeft:c.padding,marginRight:c.padding});
u=h.outerHeight(!0);h.appendTo(y);g.height+=u;break;case "over":h.css({marginLeft:c.padding,width:g.width-2*c.padding,bottom:c.padding}).appendTo(y);break;case "float":h.css("left",-1*parseInt((h.width()-g.width-40)/2,10)).appendTo(e);break;default:h.css({width:g.width-2*c.padding,paddingLeft:c.padding,paddingRight:c.padding}).appendTo(e)}h.hide();e.is(":visible")?(a(z.add(v).add(w)).hide(),b=e.position(),p={top:b.top,left:b.left,width:e.width(),height:e.height()},f=p.width==g.width&&p.height==g.height,
k.fadeTo(c.changeFade,0.3,function(){var b=function(){k.html(l.contents()).fadeTo(c.changeFade,1,K)};a.event.trigger("fancybox-change");k.empty().removeAttr("filter").css({"border-width":c.padding,width:g.width-2*c.padding,height:d.autoDimensions?"auto":g.height-u-2*c.padding});f?b():(x.prop=0,a(x).animate({prop:1},{duration:c.changeSpeed,easing:c.easingChange,step:L,complete:b}))})):(e.removeAttr("style"),k.css("border-width",c.padding),"elastic"==c.transitionIn?(p=N(),k.html(l.contents()),e.show(),
c.opacity&&(g.opacity=0),x.prop=0,a(x).animate({prop:1},{duration:c.speedIn,easing:c.easingIn,step:L,complete:K})):("inside"==c.titlePosition&&0<u&&h.show(),k.css({width:g.width-2*c.padding,height:d.autoDimensions?"auto":g.height-u-2*c.padding}).html(l.contents()),e.css(g).fadeIn("none"==c.transitionIn?0:c.speedIn,K)))}},Q=function(){(c.enableEscapeButton||c.enableKeyboardNav)&&a(document).bind("keydown.fb",function(b){if(27==b.keyCode&&c.enableEscapeButton)b.preventDefault(),a.fancybox.close();else if((37==
b.keyCode||39==b.keyCode)&&c.enableKeyboardNav&&"INPUT"!==b.target.tagName&&"TEXTAREA"!==b.target.tagName&&"SELECT"!==b.target.tagName)b.preventDefault(),a.fancybox[37==b.keyCode?"prev":"next"]()});c.showNavArrows?((c.cyclic&&1<i.length||0!==n)&&v.show(),(c.cyclic&&1<i.length||n!=i.length-1)&&w.show()):(v.hide(),w.hide())},K=function(){a.support.opacity||(k.get(0).style.removeAttribute("filter"),e.get(0).style.removeAttribute("filter"));d.autoDimensions&&k.css("height","auto");e.css("height","auto");
t&&t.length&&h.show();c.showCloseButton&&z.show();Q();c.hideOnContentClick&&k.bind("click",a.fancybox.close);c.hideOnOverlayClick&&r.bind("click",a.fancybox.close);a(window).bind("resize.fb",a.fancybox.resize);c.centerOnScroll&&a(window).bind("scroll.fb",a.fancybox.center);"iframe"==c.type&&a('<iframe id="fancybox-frame" name="fancybox-frame'+(new Date).getTime()+'" frameborder="0" hspace="0" '+(a.browser.msie?'allowtransparency="true""':"")+' scrolling="'+d.scrolling+'" src="'+c.href+'"></iframe>').appendTo(k);
e.show();j=!1;a.fancybox.center();c.onComplete(i,n,c);var b,f;i.length-1>n&&(b=i[n+1].href,"undefined"!==typeof b&&b.match(D)&&(f=new Image,f.src=b));0<n&&(b=i[n-1].href,"undefined"!==typeof b&&b.match(D)&&(f=new Image,f.src=b))},L=function(b){var a={width:parseInt(p.width+(g.width-p.width)*b,10),height:parseInt(p.height+(g.height-p.height)*b,10),top:parseInt(p.top+(g.top-p.top)*b,10),left:parseInt(p.left+(g.left-p.left)*b,10)};"undefined"!==typeof g.opacity&&(a.opacity=0.5>b?0.5:b);e.css(a);k.css({width:a.width-
2*c.padding,height:a.height-u*b-2*c.padding})},M=function(){return[a(window).width()-2*c.margin,a(window).height()-2*c.margin,a(document).scrollLeft()+c.margin,a(document).scrollTop()+c.margin]},P=function(){var b=M(),a={},e=c.autoScale,g=2*c.padding;a.width=-1<c.width.toString().indexOf("%")?parseInt(b[0]*parseFloat(c.width)/100,10):c.width+g;a.height=-1<c.height.toString().indexOf("%")?parseInt(b[1]*parseFloat(c.height)/100,10):c.height+g;if(e&&(a.width>b[0]||a.height>b[1]))if("image"==d.type||
"swf"==d.type){if(e=c.width/c.height,a.width>b[0]&&(a.width=b[0],a.height=parseInt((a.width-g)/e+g,10)),a.height>b[1])a.height=b[1],a.width=parseInt((a.height-g)*e+g,10)}else a.width=Math.min(a.width,b[0]),a.height=Math.min(a.height,b[1]);a.top=parseInt(Math.max(b[3]-20,b[3]+0.5*(b[1]-a.height-40)),10);a.left=parseInt(Math.max(b[2]-20,b[2]+0.5*(b[0]-a.width-40)),10);return a},N=function(){var b=d.orig?a(d.orig):!1,f={};b&&b.length?(f=b.offset(),f.top+=parseInt(b.css("paddingTop"),10)||0,f.left+=parseInt(b.css("paddingLeft"),
10)||0,f.top+=parseInt(b.css("border-top-width"),10)||0,f.left+=parseInt(b.css("border-left-width"),10)||0,f.width=b.width(),f.height=b.height(),f={width:f.width+2*c.padding,height:f.height+2*c.padding,top:f.top-c.padding-20,left:f.left-c.padding-20}):(b=M(),f={width:2*c.padding,height:2*c.padding,top:parseInt(b[3]+0.5*b[1],10),left:parseInt(b[2]+0.5*b[0],10)});return f},R=function(){q.is(":visible")?(a("div",q).css("top",-40*F+"px"),F=(F+1)%12):clearInterval(E)};a.fn.fancybox=function(b){if(!a(this).length)return this;
a(this).data("fancybox",a.extend({},b,a.metadata?a(this).metadata():{})).unbind("click.fb").bind("click.fb",function(b){b.preventDefault();j||(j=!0,a(this).blur(),m=[],o=0,b=a(this).attr("rel")||"",!b||""==b||"nofollow"===b?m.push(this):(m=a("a[rel="+b+"], area[rel="+b+"]"),o=m.index(this)),C())});return this};a.fancybox=function(b,c){var d;if(!j){j=!0;d="undefined"!==typeof c?c:{};m=[];o=parseInt(d.index,10)||0;if(a.isArray(b)){for(var e=0,g=b.length;e<g;e++)"object"==typeof b[e]?a(b[e]).data("fancybox",
a.extend({},d,b[e])):b[e]=a({}).data("fancybox",a.extend({content:b[e]},d));m=jQuery.merge(m,b)}else"object"==typeof b?a(b).data("fancybox",a.extend({},d,b)):b=a({}).data("fancybox",a.extend({content:b},d)),m.push(b);if(o>m.length||0>o)o=0;C()}};a.fancybox.showActivity=function(){clearInterval(E);q.show();E=setInterval(R,66)};a.fancybox.hideActivity=function(){q.hide()};a.fancybox.next=function(){return a.fancybox.pos(n+1)};a.fancybox.prev=function(){return a.fancybox.pos(n-1)};a.fancybox.pos=function(a){j||
(a=parseInt(a),m=i,-1<a&&a<i.length?(o=a,C()):c.cyclic&&1<i.length&&(o=a>=i.length?0:i.length-1,C()))};a.fancybox.cancel=function(){j||(j=!0,a.event.trigger("fancybox-cancel"),H(),d.onCancel(m,o,d),j=!1)};a.fancybox.close=function(){function b(){r.fadeOut("fast");h.empty().hide();e.hide();a.event.trigger("fancybox-cleanup");k.empty();c.onClosed(i,n,c);i=d=[];n=o=0;c=d={};j=!1}if(!j&&!e.is(":hidden"))if(j=!0,c&&!1===c.onCleanup(i,n,c))j=!1;else if(H(),a(z.add(v).add(w)).hide(),a(k.add(r)).unbind(),
a(window).unbind("resize.fb scroll.fb"),a(document).unbind("keydown.fb"),k.find("iframe").attr("src",G&&/^https/i.test(window.location.href||"")?"javascript:void(false)":"about:blank"),"inside"!==c.titlePosition&&h.empty(),e.stop(),"elastic"==c.transitionOut){p=N();var f=e.position();g={top:f.top,left:f.left,width:e.width(),height:e.height()};c.opacity&&(g.opacity=1);h.empty().hide();x.prop=1;a(x).animate({prop:0},{duration:c.speedOut,easing:c.easingOut,step:L,complete:b})}else e.fadeOut("none"==
c.transitionOut?0:c.speedOut,b)};a.fancybox.resize=function(){r.is(":visible")&&r.css("height",a(document).height());a.fancybox.center(!0)};a.fancybox.center=function(a){var d,g;if(!j&&(g=!0===a?1:0,d=M(),g||!(e.width()>d[0]||e.height()>d[1])))e.stop().animate({top:parseInt(Math.max(d[3]-20,d[3]+0.5*(d[1]-k.height()-40)-c.padding)),left:parseInt(Math.max(d[2]-20,d[2]+0.5*(d[0]-k.width()-40)-c.padding))},"number"==typeof a?a:200)};a.fancybox.init=function(){a("#fancybox-wrap").length||(a("body").append(l=
a('<div id="fancybox-tmp"></div>'),q=a('<div id="fancybox-loading"><div></div></div>'),r=a('<div id="fancybox-overlay"></div>'),e=a('<div id="fancybox-wrap"></div>')),y=a('<div id="fancybox-outer"></div>').append('<div class="fancybox-bg" id="fancybox-bg-n"></div><div class="fancybox-bg" id="fancybox-bg-ne"></div><div class="fancybox-bg" id="fancybox-bg-e"></div><div class="fancybox-bg" id="fancybox-bg-se"></div><div class="fancybox-bg" id="fancybox-bg-s"></div><div class="fancybox-bg" id="fancybox-bg-sw"></div><div class="fancybox-bg" id="fancybox-bg-w"></div><div class="fancybox-bg" id="fancybox-bg-nw"></div>').appendTo(e),
y.append(k=a('<div id="fancybox-content"></div>'),z=a('<a id="fancybox-close"></a>'),h=a('<div id="fancybox-title"></div>'),v=a('<a href="javascript:;" id="fancybox-left"><span class="fancy-ico" id="fancybox-left-ico"></span></a>'),w=a('<a href="javascript:;" id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a>')),z.click(a.fancybox.close),q.click(a.fancybox.cancel),v.click(function(b){b.preventDefault();a.fancybox.prev()}),w.click(function(b){b.preventDefault();a.fancybox.next()}),
a.fn.mousewheel&&e.bind("mousewheel.fb",function(b,c){if(j)b.preventDefault();else if(0==a(b.target).get(0).clientHeight||a(b.target).get(0).scrollHeight===a(b.target).get(0).clientHeight)b.preventDefault(),a.fancybox[0<c?"prev":"next"]()}),a.support.opacity||e.addClass("fancybox-ie"),G&&(q.addClass("fancybox-ie6"),e.addClass("fancybox-ie6"),a('<iframe id="fancybox-hide-sel-frame" src="'+(/^https/i.test(window.location.href||"")?"javascript:void(false)":"about:blank")+'" scrolling="no" border="0" frameborder="0" tabindex="-1"></iframe>').prependTo(y)))};
a.fn.fancybox.defaults={padding:10,margin:40,opacity:!1,modal:!1,cyclic:!1,scrolling:"auto",width:560,height:340,autoScale:!0,autoDimensions:!0,centerOnScroll:!1,ajax:{},swf:{wmode:"transparent"},hideOnOverlayClick:!0,hideOnContentClick:!1,overlayShow:!0,overlayOpacity:0.7,overlayColor:"#777",titleShow:!0,titlePosition:"float",titleFormat:null,titleFromAlt:!1,transitionIn:"fade",transitionOut:"fade",speedIn:300,speedOut:300,changeSpeed:300,changeFade:"fast",easingIn:"swing",easingOut:"swing",showCloseButton:!0,
showNavArrows:!0,enableEscapeButton:!0,enableKeyboardNav:!0,onStart:function(){},onCancel:function(){},onComplete:function(){},onCleanup:function(){},onClosed:function(){},onError:function(){}};a(document).ready(function(){a.fancybox.init()})})(jQuery);